import { afterEach, describe, expect, it, vi } from "vitest";
import { Block, TOWN_BLACKSMITH_STALL_POSITION, worldToChunk, getBlock } from "@blockcraft/voxel-world";
import { WorldRoom } from "../src/game-room.js";
import { InventoryItemState, MobState, PlayerState, WorldState } from "../src/schema.js";

afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); });
describe("ore to forged sword to item loot", () => {
  it("requires stall proximity and sufficient gold, buys once, auto-equips and doubles silver yield", () => {
    const room = new WorldRoom(); room.setState(new WorldState());
    const internal = room as any;
    const persist = vi.spyOn(internal, "persistPlayer").mockResolvedValue(undefined);
    vi.spyOn(internal, "recordWorldDelta").mockImplementation(() => {});
    vi.spyOn(room, "broadcast").mockImplementation(() => {});
    const player = new PlayerState(); player.coins = 12;
    room.state.players.set("buyer", player);
    const client = { sessionId: "buyer", send: vi.fn() };
    const buy = () => internal.handleBlacksmithForge(client, { upgradeId: "reinforced_pickaxe" });
    Object.assign(player, { x: 8.5, y: 8, z: 8.5 }); buy();
    expect(player.coins).toBe(12); expect(player.blacksmithUpgrades).toBe(0);
    Object.assign(player, TOWN_BLACKSMITH_STALL_POSITION); player.coins = 11; buy();
    expect(player.coins).toBe(11); expect(player.inventory.has("reinforced_pickaxe")).toBe(false);
    player.coins = 12; buy();
    expect(player.coins).toBe(0); expect(player.blacksmithUpgrades).toBe(1);
    expect(player.inventory.get("reinforced_pickaxe")?.quantity).toBe(1);
    expect(persist).toHaveBeenCalledWith("buyer", player);
    expect(client.send).toHaveBeenLastCalledWith("blacksmith:update", expect.objectContaining({ phase: "purchased", purchasedUpgradeId: "reinforced_pickaxe" }));
    player.coins = 20; buy();
    expect(player.coins).toBe(20); expect(player.inventory.get("reinforced_pickaxe")?.quantity).toBe(1);
    Object.assign(player, { x: 68.5, y: 8, z: 27.5 });
    const a = worldToChunk(68, 27); const stored = internal.getChunk(a.chunkX, a.chunkZ);
    internal.handleMine(client, { requestId: "upgraded-silver", x: 68, y: 7, z: 27, expectedRevision: stored.revision });
    expect(player.inventory.get("silver_ore")?.quantity).toBe(2);
  });
  it("mines visible silver once, preserves a full-pack block, and sells both minerals at the stall", () => {
    const room = new WorldRoom(); room.setState(new WorldState());
    const internal = room as any;
    vi.spyOn(internal, "persistPlayer").mockResolvedValue(undefined);
    vi.spyOn(internal, "recordWorldDelta").mockImplementation(() => {});
    vi.spyOn(room, "broadcast").mockImplementation(() => {});
    const player = new PlayerState(); Object.assign(player, { x: 68.5, y: 8, z: 27.5 });
    room.state.players.set("visitor", player); const client = { sessionId: "visitor", send: vi.fn() };
    const a = worldToChunk(68, 27); const stored = internal.getChunk(a.chunkX, a.chunkZ);
    const request = { requestId: "silver", x: 68, y: 7, z: 27, expectedRevision: stored.revision };
    internal.handleMine(client, request);
    expect(player.inventory.get("silver_ore")?.quantity).toBe(1);
    expect(getBlock(stored.chunk, a.localX, 7, a.localZ)).toBe(Block.Air);
    internal.handleMine(client, request);
    expect(player.inventory.get("silver_ore")?.quantity).toBe(1);
    const silver = player.inventory.get("silver_ore")!; silver.quantity = 12;
    internal.handleMine(client, { ...request, y: 6, expectedRevision: stored.revision });
    expect(getBlock(stored.chunk, a.localX, 6, a.localZ)).toBe(Block.SilverOre);
    expect(silver.quantity).toBe(12);
    const iron = new InventoryItemState(); iron.quantity = 2; player.inventory.set("iron_ore", iron);
    internal.handleBlacksmithSell(client); expect(player.coins).toBe(20);
    Object.assign(player, TOWN_BLACKSMITH_STALL_POSITION);
    internal.handleBlacksmithSell(client);
    expect(player.coins).toBe(122); expect(silver.quantity).toBe(0); expect(iron.quantity).toBe(0);
    internal.handleBlacksmithSell(client); expect(player.coins).toBe(122);
  });
  it("sells gathered ore, forges once, defeats a mob with upgraded sword damage, and collects its items", () => {
    vi.useFakeTimers(); vi.setSystemTime(10_000);
    const room = new WorldRoom(); room.setState(new WorldState());
    Object.defineProperty(room, "readWorldBlock", { value: (_x: number, y: number) => y <= 0 ? Block.Stone : Block.Air });
    const internal = room as any;
    vi.spyOn(internal, "persistPlayer").mockResolvedValue(undefined);
    vi.spyOn(room, "broadcast").mockImplementation(() => {});
    const player = new PlayerState(); Object.assign(player, TOWN_BLACKSMITH_STALL_POSITION);
    player.coins = 20; player.mainHandId = "bow";
    const ore = new InventoryItemState(); ore.quantity = 9; player.inventory.set("iron_ore", ore);
    room.state.players.set("visitor", player); const client = { sessionId: "visitor", send: vi.fn() };
    internal.handleBlacksmithSell(client);
    expect(player.coins).toBe(47); expect(ore.quantity).toBe(0);
    internal.handleBlacksmithForge(client, { upgradeId: "iron_sword" });
    expect(player.coins).toBe(2); expect(player.blacksmithUpgrades).toBe(2);
    expect(player.mainHandId).toBe("longsword"); expect(player.mainHandTag).toBe("melee");
    internal.handleBlacksmithForge(client, { upgradeId: "iron_sword" }); expect(player.coins).toBe(2);
    Object.assign(player, { x: 100.5, y: 1, z: 100.5 });
    const mob = new MobState(); Object.assign(mob, { x: 102, y: 1, z: 100.5, health: 2 });
    room.state.mobs.set("crawler", mob);
    internal.pendingAttacks.set("visitor", { requestId: "sword", mainHandId: "longsword", step: 1, yaw: 90, impactAt: 10_135 });
    internal.resolvePendingAttacks(10_225);
    expect(mob.alive).toBe(false); expect(room.state.lootDrops.size).toBe(3);
    Object.assign(player, { x: mob.x, y: mob.y, z: mob.z }); internal.resolveLootPickups(10_300);
    expect(player.inventory.get("fang_dagger")?.quantity).toBe(1);
    expect(player.inventory.get("crawler_fang")?.quantity).toBe(1);
    expect(room.state.lootDrops.size).toBe(0);
  });
});
